// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: definition/proto/job.proto

package definition

import (
	"reflect"
	"sync"

	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string      `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Request  *JobRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Executor []byte      `protobuf:"bytes,3,opt,name=executor,proto3" json:"executor,omitempty"`
}

func (x *JobEnvelope) Reset() {
	*x = JobEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobEnvelope) ProtoMessage() {}

func (x *JobEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobEnvelope.ProtoReflect.Descriptor instead.
func (*JobEnvelope) Descriptor() ([]byte, []int) {
	return file_definition_proto_job_proto_rawDescGZIP(), []int{0}
}

func (x *JobEnvelope) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *JobEnvelope) GetRequest() *JobRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *JobEnvelope) GetExecutor() []byte {
	if x != nil {
		return x.Executor
	}
	return nil
}

type JobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source      string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	CallbackUrl string `protobuf:"bytes,2,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_job_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_job_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_definition_proto_job_proto_rawDescGZIP(), []int{1}
}

func (x *JobRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *JobRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

var File_definition_proto_job_proto protoreflect.FileDescriptor

var file_definition_proto_job_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6a, 0x6f,
	0x62, 0x22, 0x64, 0x0a, 0x0b, 0x4a, 0x6f, 0x62, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x29, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x65,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x22, 0x47, 0x0a, 0x0a, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x72, 0x6c,
	0x42, 0x14, 0x5a, 0x12, 0x72, 0x6f, 0x6d, 0x75, 0x73, 0x68, 0x61, 0x2f, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_definition_proto_job_proto_rawDescOnce sync.Once
	file_definition_proto_job_proto_rawDescData = file_definition_proto_job_proto_rawDesc
)

func file_definition_proto_job_proto_rawDescGZIP() []byte {
	file_definition_proto_job_proto_rawDescOnce.Do(func() {
		file_definition_proto_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_definition_proto_job_proto_rawDescData)
	})
	return file_definition_proto_job_proto_rawDescData
}

var file_definition_proto_job_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_definition_proto_job_proto_goTypes = []interface{}{
	(*JobEnvelope)(nil), // 0: job.JobEnvelope
	(*JobRequest)(nil),  // 1: job.JobRequest
}
var file_definition_proto_job_proto_depIdxs = []int32{
	1, // 0: job.JobEnvelope.request:type_name -> job.JobRequest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_definition_proto_job_proto_init() }
func file_definition_proto_job_proto_init() {
	if File_definition_proto_job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_definition_proto_job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_definition_proto_job_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_definition_proto_job_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_definition_proto_job_proto_goTypes,
		DependencyIndexes: file_definition_proto_job_proto_depIdxs,
		MessageInfos:      file_definition_proto_job_proto_msgTypes,
	}.Build()
	File_definition_proto_job_proto = out.File
	file_definition_proto_job_proto_rawDesc = nil
	file_definition_proto_job_proto_goTypes = nil
	file_definition_proto_job_proto_depIdxs = nil
}
