// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: definition/proto/participant.proto

package definition

import (
	"reflect"
	"sync"

	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Topic int32

const (
	Topic_Call             Topic = 0
	Topic_Join             Topic = 1
	Topic_Busy             Topic = 2
	Topic_BroadcastFailure Topic = 3
	Topic_BroadcastSuccess Topic = 4
)

// Enum value maps for Topic.
var (
	Topic_name = map[int32]string{
		0: "Call",
		1: "Join",
		2: "Busy",
		3: "BroadcastFailure",
		4: "BroadcastSuccess",
	}
	Topic_value = map[string]int32{
		"Call":             0,
		"Join":             1,
		"Busy":             2,
		"BroadcastFailure": 3,
		"BroadcastSuccess": 4,
	}
)

func (x Topic) Enum() *Topic {
	p := new(Topic)
	*p = x
	return p
}

func (x Topic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Topic) Descriptor() protoreflect.EnumDescriptor {
	return file_definition_proto_participant_proto_enumTypes[0].Descriptor()
}

func (Topic) Type() protoreflect.EnumType {
	return &file_definition_proto_participant_proto_enumTypes[0]
}

func (x Topic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Topic.Descriptor instead.
func (Topic) EnumDescriptor() ([]byte, []int) {
	return file_definition_proto_participant_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_Unknown   Status = 0
	Status_Available Status = 1
	Status_Occupied  Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Unknown",
		1: "Available",
		2: "Occupied",
	}
	Status_value = map[string]int32{
		"Unknown":   0,
		"Available": 1,
		"Occupied":  2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_definition_proto_participant_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_definition_proto_participant_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_definition_proto_participant_proto_rawDescGZIP(), []int{1}
}

type Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *Member) Reset() {
	*x = Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_definition_proto_participant_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_definition_proto_participant_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_definition_proto_participant_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

var File_definition_proto_participant_proto protoreflect.FileDescriptor

var file_definition_proto_participant_proto_rawDesc = []byte{
	0x0a, 0x22, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e,
	0x74, 0x22, 0x1c, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x2a,
	0x51, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x61, 0x6c, 0x6c,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x42, 0x75, 0x73, 0x79, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63,
	0x61, 0x73, 0x74, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10,
	0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x10, 0x04, 0x2a, 0x32, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x63, 0x63, 0x75,
	0x70, 0x69, 0x65, 0x64, 0x10, 0x02, 0x42, 0x14, 0x5a, 0x12, 0x72, 0x6f, 0x6d, 0x75, 0x73, 0x68,
	0x61, 0x2f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_definition_proto_participant_proto_rawDescOnce sync.Once
	file_definition_proto_participant_proto_rawDescData = file_definition_proto_participant_proto_rawDesc
)

func file_definition_proto_participant_proto_rawDescGZIP() []byte {
	file_definition_proto_participant_proto_rawDescOnce.Do(func() {
		file_definition_proto_participant_proto_rawDescData = protoimpl.X.CompressGZIP(file_definition_proto_participant_proto_rawDescData)
	})
	return file_definition_proto_participant_proto_rawDescData
}

var file_definition_proto_participant_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_definition_proto_participant_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_definition_proto_participant_proto_goTypes = []interface{}{
	(Topic)(0),     // 0: participant.Topic
	(Status)(0),    // 1: participant.Status
	(*Member)(nil), // 2: participant.Member
}
var file_definition_proto_participant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_definition_proto_participant_proto_init() }
func file_definition_proto_participant_proto_init() {
	if File_definition_proto_participant_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_definition_proto_participant_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_definition_proto_participant_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_definition_proto_participant_proto_goTypes,
		DependencyIndexes: file_definition_proto_participant_proto_depIdxs,
		EnumInfos:         file_definition_proto_participant_proto_enumTypes,
		MessageInfos:      file_definition_proto_participant_proto_msgTypes,
	}.Build()
	File_definition_proto_participant_proto = out.File
	file_definition_proto_participant_proto_rawDesc = nil
	file_definition_proto_participant_proto_goTypes = nil
	file_definition_proto_participant_proto_depIdxs = nil
}
